name: Build ssh-para binary (manylinux/macos)

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build-linux-x86_64:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y ruby ruby-dev build-essential rpm
          sudo gem install --no-document fpm

      - name: Set version
        run: |
          if [ "${{ github.event_name }}" = "release" ]; then
            echo "VERSION=${{ github.event.release.tag_name }}" >> $GITHUB_ENV
          else
            echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
          fi
          echo "ARCH=x86_64"
          echo "TOOL=ssh-para" >> $GITHUB_ENV
          echo "TOOL_PATH=dist/ssh-para-linux-x86_64" >>$GITHUB_ENV
          echo "DESC=parallel ssh job manager" >> $GITHUB_ENV

      - name: Build with manylinux (x86_64)
        run: |
          set -e

          IMAGE=quay.io/pypa/manylinux2014_x86_64
          OUT=ssh-para-linux-x86_64

          docker run --rm \
            -v "$PWD:/src" \
            $IMAGE \
            bash -c "
              set -e
              cd /opt/_internal
              tar xf static-libs-for-embedding-only.tar.xz
              yum install -y ncurses ncurses-devel

              cd /src

              # Choose a specific Python version available in manylinux
              PYBIN=/opt/python/cp311-cp311/bin/python

              \$PYBIN -m venv .venv
              source .venv/bin/activate
              pip install pyinstaller ssh-para

              pyinstaller --onefile --add-data-dir=/usr/share/terminfo=terminfo --name=$OUT ssh_para/ssh_para.py
            "

      - name: Build DEB
        run: |
          fpm -s dir -t deb --license=MIT --maintainer=joknarf --prefix=/usr -m joknarf@free.fr --description="$DESC" -n $TOOL -v $VERSION --url=https://github.com/joknarf/$TOOL $TOOL_PATH=/bin/$TOOL
          ln -s ${TOOL}_${VERSION}_amd64.deb ${TOOL}_amd64.deb

      - name: Build RPM
        run: |
          fpm -s dir -t rpm --license=MIT --maintainer=joknarf --prefix=/usr -m joknarf@free.fr --description="$DESC" -n $TOOL -v $VERSION --url=https://github.com/joknarf/$TOOL $TOOL_PATH=/bin/$TOOL
          ln -s $TOOL-$VERSION-1.x86_64.rpm $TOOL-x86_64.rpm

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: ssh-para[_-]* dist/ssh-para*

  build-linux-aarch64:
    runs-on: ubuntu-24.04-arm

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Build with manylinux (aarch64)
        run: |
          set -e

          IMAGE=quay.io/pypa/manylinux2014_aarch64
          OUT=ssh-para-linux-aarch64

          docker run --rm \
            -v "$PWD:/src" \
            $IMAGE \
            bash -c "
              set -e
              cd /opt/_internal
              tar xf static-libs-for-embedding-only.tar.xz

              cd /src

              # Choose a specific Python version available in manylinux
              PYBIN=/opt/python/cp311-cp311/bin/python

              \$PYBIN -m pip install --upgrade pip
              \$PYBIN -m pip install nuitka ssh-para

              \$PYBIN -m nuitka --onefile --follow-imports --assume-yes-for-downloads --output-filename=$OUT --main=ssh_para/ssh_para.py
            "

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: ssh-para-linux-*

  build-macos-x86_64:
    runs-on: macos-15-intel

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Build with Nuitka
        run: |
          set -e

          OUT=ssh-para-macos-x86-64

          python -m pip install --upgrade pip
          python -m pip install nuitka ssh-para

          python -m nuitka --onefile --follow-imports --assume-yes-for-downloads --output-filename=$OUT --main=ssh_para/ssh_para.py

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: ssh-para-macos-*

  build-macos-arm64:
    runs-on: macos-14

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Build with Nuitka
        run: |
          set -e

          OUT=ssh-para-macos-arm64

          python -m pip install --upgrade pip
          python -m pip install nuitka ssh-para

          python -m nuitka --onefile --follow-imports --assume-yes-for-downloads --output-filename=$OUT --main=ssh_para/ssh_para.py

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: ssh-para-macos-*

